// Cheat code data for AJC's Cheat Codes.
// Verified against 2+ independent sources per entry (Rockstar-focused
// guides, GTA Wiki-adjacent outlets, PCGamer, GamesRadar, GTABase,
// RDR2.org, etc). pc / console hold the exact code/phrase to show on
// each tab. Where a game's cheat system doesn't actually differ between
// PC and console (GTA IV's phone numbers, RDR2's text phrases), pc and
// console intentionally hold the same value rather than a fabricated
// difference. For GTA V, "console" combines the PS and Xbox
// button-combo strings since they use different face-button names for
// the same input. `extra` carries the equivalent in-game-phone number
// as a secondary, easier-to-remember entry method where one exists.

function gta5Cheat({ id, name, description, category, pc, consolePS, consoleXbox, phone, console, note }) {
  return {
    id,
    name,
    description,
    category,
    pc,
    console: console || `${consolePS}\n${consoleXbox}`,
    extra: phone ? `Phone: ${phone}` : note,
  };
}

const CHEAT_DATA = {
  gta5: {
    pcNote:
      'Type these on your keyboard during gameplay (or dial the phone number below on your in-game phone).',
    consoleNote:
      'Enter these as a quick D-pad + face-button combo while walking around, not paused. PS and Xbox layouts differ, so both are shown.',
    cheats: [
      gta5Cheat({
        id: 'invincibility',
        name: 'Invincibility / God Mode',
        description: 'Makes your character immune to all damage for about five minutes.',
        category: 'Player',
        pc: 'PAINKILLER',
        consolePS: 'PS: Right, X, Right, Left, Right, R1, Right, Left, X, Triangle',
        consoleXbox: 'Xbox: Right, A, Right, Left, Right, RB, Right, Left, A, Y',
        phone: '1-999-724-654-5537 (1-999-PAIN-KILLER)',
      }),
      gta5Cheat({
        id: 'max-health-armor',
        name: 'Max Health & Armor',
        description: 'Instantly restores full health and gives full body armor.',
        category: 'Player',
        pc: 'TURTLE',
        consolePS: 'PS: Circle, L1, Triangle, R2, X, Square, Circle, Right, Square, L1, L1, L1',
        consoleXbox: 'Xbox: B, LB, Y, RT, A, X, B, Right, X, LB, LB, LB',
        phone: '1-999-887-853 (1-999-TURTLE)',
      }),
      gta5Cheat({
        id: 'give-weapons',
        name: 'Give Weapons & Ammo',
        description:
          'Grants a full set of weapons (pistol, SMG, assault rifle, sniper rifle, RPG, grenades, and more) with refilled ammo.',
        category: 'Weapons',
        pc: 'TOOLUP',
        consolePS: 'PS: Triangle, R2, Left, L1, X, Right, Triangle, Down, Square, L1, L1, L1',
        consoleXbox: 'Xbox: Y, RT, Left, LB, A, Right, Y, Down, X, LB, LB, LB',
        phone: '1-999-866-587 (1-999-TOOL-UP)',
      }),
      gta5Cheat({
        id: 'super-jump',
        name: 'Super Jump',
        description:
          'Lets your character leap far higher than normal; hold the jump button longer for extra height.',
        category: 'Player',
        pc: 'HOPTOIT',
        consolePS: 'PS: Left, Left, Triangle, Triangle, Right, Right, Left, Right, Square, R1, R2',
        consoleXbox: 'Xbox: Left, Left, Y, Y, Right, Right, Left, Right, X, RB, RT',
        phone: '1-999-467-8648 (1-999-HOP-TO-IT)',
      }),
      gta5Cheat({
        id: 'skyfall',
        name: 'Skyfall',
        description:
          'Drops your character from roughly a mile in the air and equips a parachute so you can glide safely down.',
        category: 'World/Misc',
        pc: 'SKYFALL',
        consolePS: 'PS: L1, L2, R1, R2, Left, Right, Left, Right, L1, L2, R1, R2, Left, Right, Left, Right',
        consoleXbox: 'Xbox: LB, LT, RB, RT, Left, Right, Left, Right, LB, LT, RB, RT, Left, Right, Left, Right',
        phone: '1-999-759-3255 (1-999-SKYFALL)',
      }),
      gta5Cheat({
        id: 'drunk-mode',
        name: 'Drunk Mode',
        description:
          'Makes your character stumble, slur speech, and lose steady control of movement and vehicles as if intoxicated.',
        category: 'World/Misc',
        pc: 'LIQUOR',
        consolePS: 'PS: Triangle, Right, Right, Left, Right, Square, Circle, Left',
        consoleXbox: 'Xbox: Y, Right, Right, Left, Right, X, B, Left',
        phone: '1-999-547-861 (1-999-LIQUOR)',
      }),
      gta5Cheat({
        id: 'slow-motion',
        name: 'Slow Motion',
        description:
          'Slows down time; enter up to three more times to deepen the effect, then once more to return to normal.',
        category: 'World/Misc',
        pc: 'SLOWMO',
        consolePS: 'PS: Triangle, Left, Right, Right, Square, R2, R1',
        consoleXbox: 'Xbox: Y, Left, Right, Right, X, RT, RB',
        phone: '1-999-756-966 (1-999-SLOW-MO)',
      }),
      gta5Cheat({
        id: 'recharge-special-ability',
        name: 'Recharge Special Ability',
        description:
          "Instantly refills the current character's special-ability meter (Michael's Focus, Franklin's driving slow-mo, or Trevor's Rage).",
        category: 'Player',
        pc: 'POWERUP',
        consolePS: 'PS: X, X, Square, R1, L1, X, Right, Left, X',
        consoleXbox: 'Xbox: A, A, X, RB, LB, A, Right, Left, A',
        phone: '1-999-769-3787 (1-999-POWER-UP)',
      }),
      gta5Cheat({
        id: 'moon-gravity',
        name: 'Moon Gravity',
        description: 'Reduces gravity so people and vehicles float and jump much higher than normal.',
        category: 'World/Misc',
        pc: 'FLOATER',
        consolePS: 'PS: Left, Left, L1, R1, L1, Right, Left, L1, Left',
        consoleXbox: 'Xbox: Left, Left, LB, RB, LB, Right, Left, LB, Left',
        phone: '1-999-356-2837 (1-999-FLOATER)',
      }),
      gta5Cheat({
        id: 'raise-wanted-level',
        name: 'Raise Wanted Level',
        description: 'Adds one star to your current wanted level; can be repeated up to the five-star maximum.',
        category: 'Wanted Level',
        pc: 'FUGITIVE',
        consolePS: 'PS: R1, R1, Circle, R2, Left, Right, Left, Right, Left, Right',
        consoleXbox: 'Xbox: RB, RB, B, RT, Left, Right, Left, Right, Left, Right',
        phone: '1-999-384-48483 (1-999-FUGITIVE)',
      }),
      gta5Cheat({
        id: 'lower-wanted-level',
        name: 'Lower Wanted Level',
        description: 'Removes one star from your current wanted level; can be repeated to clear it entirely.',
        category: 'Wanted Level',
        pc: 'LAWYERUP',
        consolePS: 'PS: R1, R1, Circle, R2, Right, Left, Right, Left, Right, Left',
        consoleXbox: 'Xbox: RB, RB, B, RT, Right, Left, Right, Left, Right, Left',
        phone: '1-999-529-93787 (1-999-LAWYER-UP)',
      }),
      gta5Cheat({
        id: 'spawn-bmx',
        name: 'Spawn BMX',
        description: 'Instantly spawns a BMX bicycle right next to your character.',
        category: 'Vehicles',
        pc: 'BANDIT',
        consolePS: 'PS: Left, Left, Right, Right, Left, Right, Square, Circle, Triangle, R1, R2',
        consoleXbox: 'Xbox: Left, Left, Right, Right, Left, Right, X, B, Y, RB, RT',
        phone: '1-999-226-348 (1-999-BANDIT)',
      }),
      gta5Cheat({
        id: 'spawn-sanchez',
        name: 'Spawn Sanchez Dirt Bike',
        description: 'Instantly spawns a Sanchez off-road dirt bike right next to your character.',
        category: 'Vehicles',
        pc: 'OFFROAD',
        consolePS: 'PS: Circle, X, L1, Circle, Circle, L1, Circle, R1, R2, L2, L1, L1',
        consoleXbox: 'Xbox: B, A, LB, B, B, LB, B, RB, RT, LT, LB, LB',
        phone: '1-999-633-7623 (1-999-OFFROAD)',
      }),
      gta5Cheat({
        id: 'spawn-trashmaster',
        name: 'Spawn Trashmaster',
        description: 'Instantly spawns a Trashmaster garbage truck right next to your character.',
        category: 'Vehicles',
        pc: 'TRASHED',
        consolePS: 'PS: Circle, R1, Circle, R1, Left, Left, R1, L1, Circle, Right',
        consoleXbox: 'Xbox: B, RB, B, RB, Left, Left, RB, LB, B, Right',
        phone: '1-999-872-433 (1-999-TRASHED)',
      }),
      gta5Cheat({
        id: 'spawn-buzzard',
        name: 'Spawn Buzzard Attack Chopper',
        description: 'Instantly spawns a Buzzard attack helicopter right next to your character.',
        category: 'Vehicles',
        pc: 'BUZZOFF',
        consolePS: 'PS: Circle, Circle, L1, Circle, Circle, Circle, L1, L2, R1, Triangle, Circle, Triangle',
        consoleXbox: 'Xbox: B, B, LB, B, B, B, LB, LT, RB, Y, B, Y',
        phone: '1-999-289-9633 (1-999-BUZZ-OFF)',
      }),
      gta5Cheat({
        id: 'spawn-rapidgt',
        name: 'Spawn Rapid GT',
        description: 'Instantly spawns a Rapid GT sports car right next to your character.',
        category: 'Vehicles',
        pc: 'RAPIDGT',
        consolePS: 'PS: R1, Right, Left, Right, R2, Left, Right, Square, Right, L2, L1, L1',
        consoleXbox: 'Xbox: RB, Right, Left, Right, RT, Left, Right, X, Right, LT, LB, LB',
        phone: '1-999-727-4348 (1-999-RAPID-GT)',
      }),
      gta5Cheat({
        id: 'explosive-rounds',
        name: 'Explosive Rounds',
        description: 'Makes every bullet you fire explode on impact.',
        category: 'Weapons',
        pc: 'HIGHEX',
        consolePS: 'PS: Right, Square, X, Left, R1, R2, Left, Right, Right, L1, L1, L1',
        consoleXbox: 'Xbox: Right, X, A, Left, RB, RT, Left, Right, Right, LB, LB, LB',
        phone: '1-999-444-439 (1-999-HIGH-EX)',
      }),
      gta5Cheat({
        id: 'flaming-bullets',
        name: 'Flaming Bullets',
        description: 'Sets your bullets on fire so they ignite whatever they hit.',
        category: 'Weapons',
        pc: 'INCENDIARY',
        consolePS: 'PS: L1, R1, Square, R1, Left, R2, R1, Left, Square, Right, L1, L1',
        consoleXbox: 'Xbox: LB, RB, X, RB, Left, RT, RB, Left, X, Right, LB, LB',
        phone: '1-999-462-363-4279 (1-999-INCENDIARY)',
      }),
      gta5Cheat({
        id: 'explosive-melee',
        name: 'Explosive Melee Attacks',
        description: 'Makes unarmed melee hits explode on contact (only works with no weapon equipped).',
        category: 'Weapons',
        pc: 'HOTHANDS',
        console: '1-999-468-42637',
        note: 'No controller combo could be verified across sources, so the phone number (1-999-HOT-HANDS) is used here too.',
      }),
      gta5Cheat({
        id: 'change-weather',
        name: 'Change Weather',
        description: 'Cycles the current weather through sunny, cloudy, foggy, rainy, and stormy conditions.',
        category: 'World/Misc',
        pc: 'MAKEITRAIN',
        console: '1-999-625-348-7246',
        note: 'No controller combo could be verified across sources, so the phone number (1-999-MAKE-IT-RAIN) is used here too.',
      }),
    ],
  },

  gta4: {
    pcNote: "Dial this number on Niko's in-game phone (bring up the phone, open the keypad, dial, then call).",
    consoleNote: "Dial this number on Niko's in-game phone with the d-pad — identical to the PC code.",
    cheats: [
      {
        id: 'health-armor-weapons',
        name: 'Full Health, Armor, Weapons & Vehicle Repair',
        description:
          "Fully restores Niko's health and armor, refills ammo for his current weapons, and repairs the vehicle he's in.",
        category: 'Player',
        pc: '482-555-0100',
        console: '482-555-0100',
      },
      {
        id: 'health-repair-only',
        name: 'Health & Vehicle Repair',
        description: "Restores Niko's health and repairs the vehicle he's currently in, without touching weapons.",
        category: 'Player',
        pc: '362-555-0100',
        console: '362-555-0100',
      },
      {
        id: 'weapons-pack-basic',
        name: 'Weapons Pack 1',
        description:
          'Gives Niko a first tier of weapons including a knife, pistol, shotgun, SMG, assault rifle, sniper rifle, Molotovs, and an RPG.',
        category: 'Weapons',
        pc: '486-555-0150',
        console: '486-555-0150',
      },
      {
        id: 'weapons-pack-advanced',
        name: 'Weapons Pack 2',
        description:
          'Gives Niko a heavier tier of weapons including a baseball bat, combat pistol, combat shotgun, SMG, carbine rifle, sniper rifle, and grenades.',
        category: 'Weapons',
        pc: '486-555-0100',
        console: '486-555-0100',
      },
      {
        id: 'remove-wanted-level',
        name: 'Remove Wanted Level',
        description: "Instantly clears Niko's wanted level down to zero stars.",
        category: 'Wanted Level',
        pc: '267-555-0100',
        console: '267-555-0100',
      },
      {
        id: 'raise-wanted-level',
        name: 'Raise Wanted Level',
        description: "Adds an extra star to Niko's current wanted level.",
        category: 'Wanted Level',
        pc: '267-555-0150',
        console: '267-555-0150',
      },
      {
        id: 'spawn-annihilator',
        name: 'Spawn Annihilator Helicopter',
        description: "Spawns an Annihilator attack helicopter near Niko's location.",
        category: 'Vehicles',
        pc: '359-555-0100',
        console: '359-555-0100',
      },
      {
        id: 'spawn-jetmax',
        name: 'Spawn Jetmax',
        description: 'Spawns a Jetmax speedboat near the nearest waterway.',
        category: 'Vehicles',
        pc: '938-555-0100',
        console: '938-555-0100',
      },
      {
        id: 'spawn-turismo',
        name: 'Spawn Turismo',
        description: "Spawns a Turismo sports car near Niko's location.",
        category: 'Vehicles',
        pc: '227-555-0147',
        console: '227-555-0147',
      },
      {
        id: 'spawn-comet',
        name: 'Spawn Comet',
        description: "Spawns a Comet sports car near Niko's location.",
        category: 'Vehicles',
        pc: '227-555-0175',
        console: '227-555-0175',
      },
      {
        id: 'spawn-cognoscenti',
        name: 'Spawn Cognoscenti',
        description: "Spawns a Cognoscenti luxury sedan near Niko's location.",
        category: 'Vehicles',
        pc: '227-555-0142',
        console: '227-555-0142',
      },
      {
        id: 'spawn-supergt',
        name: 'Spawn SuperGT',
        description: "Spawns a SuperGT sports car near Niko's location.",
        category: 'Vehicles',
        pc: '227-555-0168',
        console: '227-555-0168',
      },
      {
        id: 'spawn-fbi-buffalo',
        name: 'Spawn FBI Buffalo',
        description: "Spawns an FBI Buffalo (unmarked police muscle car) near Niko's location.",
        category: 'Vehicles',
        pc: '227-555-0100',
        console: '227-555-0100',
      },
      {
        id: 'spawn-nrg900',
        name: 'Spawn NRG-900',
        description: "Spawns an NRG-900 sport motorcycle near Niko's location.",
        category: 'Vehicles',
        pc: '625-555-0100',
        console: '625-555-0100',
      },
      {
        id: 'spawn-sanchez',
        name: 'Spawn Sanchez Dirt Bike',
        description: "Spawns a Sanchez off-road dirt bike near Niko's location.",
        category: 'Vehicles',
        pc: '625-555-0150',
        console: '625-555-0150',
      },
      {
        id: 'change-weather',
        name: 'Change Weather',
        description: "Cycles Liberty City's weather between stormy, clear, overcast, foggy, and sunny.",
        category: 'World/Misc',
        pc: '468-555-0100',
        console: '468-555-0100',
      },
      {
        id: 'nikos-original-hair',
        name: "Niko's Original Hair",
        description: "Resets Niko's hairstyle back to his original default look.",
        category: 'World/Misc',
        pc: '288-555-0100',
        console: '288-555-0100',
      },
    ],
  },

  rdr2: {
    pcNote:
      "Pause > Settings, then press Enter to open the Cheats box and type the phrase exactly (punctuation matters, capitalization doesn't).",
    consoleNote:
      'Pause > Settings, then press Triangle (PS) or Y (Xbox) to open the Cheats box and enter the same phrase.',
    cheats: [
      {
        id: 'infinite-ammo',
        name: 'Infinite Ammo',
        description: 'Gives Arthur/John unlimited ammunition for all carried weapons.',
        category: 'Weapons',
        pc: 'Abundance is the dullest desire',
        console: 'Abundance is the dullest desire',
      },
      {
        id: 'heavy-weapons-set',
        name: 'Heavy Weapons Set',
        description:
          'Adds a Pump-Action Shotgun, Bolt Action Rifle, Mauser Pistol, and Semi-Automatic Pistol to your inventory.',
        category: 'Weapons',
        pc: 'Greed is American Virtue',
        console: 'Greed is American Virtue',
      },
      {
        id: 'gunslinger-weapons-set',
        name: 'Gunslinger Weapons Set',
        description:
          'Adds an off-hand holster plus a Double-Action Revolver, Schofield Revolver, and Double-Barreled Shotgun to your inventory.',
        category: 'Weapons',
        pc: 'History is written by fools',
        console: 'History is written by fools',
      },
      {
        id: 'refill-health-stamina-deadeye',
        name: 'Refill Health, Stamina & Dead Eye',
        description: 'Instantly refills the Health, Stamina, and Dead Eye core meters.',
        category: 'Player',
        pc: 'You flourish before you die',
        console: 'You flourish before you die',
      },
      {
        id: 'god-mode',
        name: 'God Mode',
        description: 'Fortifies the Health, Stamina, and Dead Eye cores so they stay full while the cheat is active.',
        category: 'Player',
        pc: 'You seek more than the world offers',
        console: 'You seek more than the world offers',
      },
      {
        id: 'extra-money',
        name: 'Give $500',
        description: 'Adds $500 in cash to your wallet; can be entered repeatedly for more money.',
        category: 'World/Misc',
        pc: 'Greed is now a virtue',
        console: 'Greed is now a virtue',
      },
      {
        id: 'decrease-wanted-level',
        name: 'Decrease Wanted Level',
        description: 'Immediately lowers your current wanted level.',
        category: 'Wanted Level',
        pc: 'You want freedom',
        console: 'You want freedom',
      },
      {
        id: 'clear-bounty',
        name: 'Clear Bounty & Notoriety',
        description: "Removes all of Arthur's active bounties and clears his notoriety/lockdown status.",
        category: 'Wanted Level',
        pc: 'You want everyone to go away',
        console: 'You want everyone to go away',
      },
      {
        id: 'spawn-war-horse',
        name: 'Spawn War Horse',
        description: 'Instantly spawns a War Horse at your location.',
        category: 'Vehicles',
        pc: 'You are a beast built for war',
        console: 'You are a beast built for war',
      },
      {
        id: 'spawn-superior-horse',
        name: 'Spawn Superior Horse',
        description: 'Instantly spawns a Rose Grey Bay Arabian horse at your location.',
        category: 'Vehicles',
        pc: 'You want more than you have',
        console: 'You want more than you have',
      },
      {
        id: 'spawn-random-horse',
        name: 'Spawn Random Horse',
        description: 'Instantly spawns a horse of a random breed at your location.',
        category: 'Vehicles',
        pc: 'You want something new',
        console: 'You want something new',
      },
      {
        id: 'spawn-wagon',
        name: 'Spawn Wagon',
        description: 'Instantly spawns a horse-drawn wagon at your location.',
        category: 'Vehicles',
        pc: 'Keep your dreams simple',
        console: 'Keep your dreams simple',
      },
      {
        id: 'reveal-map',
        name: 'Reveal Full Map',
        description: 'Reveals the entire world map, permanently clearing the fog of war even after the cheat is toggled off.',
        category: 'World/Misc',
        pc: 'You long for sight but see nothing',
        console: 'You long for sight but see nothing',
      },
      {
        id: 'unlock-crafting-recipes',
        name: 'Unlock All Crafting Recipes',
        description: 'Instantly teaches every crafting recipe in the game (ingredients are still required to actually craft).',
        category: 'World/Misc',
        pc: 'Eat of knowledge',
        console: 'Eat of knowledge',
      },
    ],
  },
};

const GAMES = [
  {
    id: 'gta5',
    title: 'Grand Theft Auto V',
    shortTitle: 'GTA V',
    subtitle: 'Los Santos & Blaine County',
  },
  {
    id: 'gta4',
    title: 'Grand Theft Auto IV',
    shortTitle: 'GTA IV',
    subtitle: 'Liberty City',
  },
  {
    id: 'rdr2',
    title: 'Red Dead Redemption 2',
    shortTitle: 'RDR2',
    subtitle: 'The Old West, 1899',
  },
];
