// Theme definitions for each game. Each theme drives color, font, and
// texture choices so every screen feels like a distinct, intentional skin
// rather than a palette swap.

export const THEME_IDS = {
  DEFAULT: 'default',
  GTA5: 'gta5',
  GTA4: 'gta4',
  RDR2: 'rdr2',
};

const base = {
  radius: 14,
  cardRadius: 16,
};

export const themes = {
  [THEME_IDS.DEFAULT]: {
    ...base,
    id: THEME_IDS.DEFAULT,
    name: "AJC's Cheat Codes",
    background: '#0E0F13',
    backgroundGradient: ['#14161D', '#0A0A0D'],
    surface: '#1B1D25',
    surfaceAlt: '#22242E',
    border: '#2E313D',
    accent: '#F2C230',
    accentAlt: '#F2C230',
    textPrimary: '#F5F5F5',
    textSecondary: '#9A9DAA',
    tabActiveBg: '#F2C230',
    tabActiveText: '#0E0F13',
    tabInactiveBg: '#1B1D25',
    tabInactiveText: '#9A9DAA',
    fontDisplay: null,
    fontBody: null,
    fontMono: null,
    letterSpacingDisplay: 1,
    statusBarStyle: 'light',
    categoryTint: '#2A2C36',
  },

  // GTA V — black background, matrix/hacker green, digital-terminal feel
  [THEME_IDS.GTA5]: {
    ...base,
    id: THEME_IDS.GTA5,
    name: 'Grand Theft Auto V',
    shortName: 'GTA V',
    background: '#000000',
    backgroundGradient: ['#0A0F0A', '#000000'],
    surface: '#0B120C',
    surfaceAlt: '#101A11',
    border: '#1E3B22',
    accent: '#39FF6A',
    accentAlt: '#1DB954',
    textPrimary: '#D8FFDE',
    textSecondary: '#5FAE71',
    tabActiveBg: '#39FF6A',
    tabActiveText: '#000000',
    tabInactiveBg: '#0B120C',
    tabInactiveText: '#5FAE71',
    fontDisplay: 'ShareTechMono_400Regular',
    fontBody: 'ShareTechMono_400Regular',
    fontMono: 'ShareTechMono_400Regular',
    letterSpacingDisplay: 2,
    statusBarStyle: 'light',
    categoryTint: '#122015',
    glow: '#39FF6A',
  },

  // GTA IV — Liberty City noir: dark navy/steel with amber-orange accents
  [THEME_IDS.GTA4]: {
    ...base,
    id: THEME_IDS.GTA4,
    name: 'Grand Theft Auto IV',
    shortName: 'GTA IV',
    background: '#0B0F17',
    backgroundGradient: ['#111826', '#080B12'],
    surface: '#141C2B',
    surfaceAlt: '#1A2434',
    border: '#2A3B52',
    accent: '#FF8C2B',
    accentAlt: '#F2A65A',
    textPrimary: '#EAF0F8',
    textSecondary: '#7E92AC',
    tabActiveBg: '#FF8C2B',
    tabActiveText: '#0B0F17',
    tabInactiveBg: '#141C2B',
    tabInactiveText: '#7E92AC',
    fontDisplay: 'Oswald_600SemiBold',
    fontBody: 'Oswald_400Regular',
    fontMono: 'Oswald_500Medium',
    letterSpacingDisplay: 1.5,
    statusBarStyle: 'light',
    categoryTint: '#1B2536',
  },

  // RDR2 — bone-white wanted-poster with dried-blood red accents, western serif
  [THEME_IDS.RDR2]: {
    ...base,
    id: THEME_IDS.RDR2,
    name: 'Red Dead Redemption 2',
    shortName: 'RDR2',
    background: '#F4EEDD',
    backgroundGradient: ['#FBF7EC', '#EDE4CC'],
    surface: '#FFFDF6',
    surfaceAlt: '#EAE0C6',
    border: '#C9B98F',
    accent: '#8A1F11',
    accentAlt: '#6E170C',
    textPrimary: '#2B2015',
    textSecondary: '#6B5A3E',
    tabActiveBg: '#8A1F11',
    tabActiveText: '#FBF7EC',
    tabInactiveBg: '#EFE7CF',
    tabInactiveText: '#6B5A3E',
    fontDisplay: 'Rye_400Regular',
    fontBody: 'Merriweather_400Regular',
    fontMono: 'SpecialElite_400Regular',
    letterSpacingDisplay: 1,
    statusBarStyle: 'dark',
    categoryTint: '#E7DBB8',
  },
};

export const games = [
  {
    id: THEME_IDS.GTA5,
    title: 'Grand Theft Auto V',
    subtitle: 'Los Santos & Blaine County',
    theme: themes[THEME_IDS.GTA5],
  },
  {
    id: THEME_IDS.GTA4,
    title: 'Grand Theft Auto IV',
    subtitle: 'Liberty City',
    theme: themes[THEME_IDS.GTA4],
  },
  {
    id: THEME_IDS.RDR2,
    title: 'Red Dead Redemption 2',
    subtitle: 'The Old West, 1899',
    theme: themes[THEME_IDS.RDR2],
  },
];
